<?php
/**
 * @file
 *  
 */
 
// TODO GUI FOR CREATING FEATURE SETS W/ LINKS IN CONTROL PANEL
// TODO Make control panel stuff exportable with features

/**
 * Implementation of hook_help()
 */
function fcontrolpanel_help($path, $arg) {
  if ($path == 'admin/help#fcontrolpanel') {
    $txt = 'Features Control Panel provides a.... [FINISH HELP TEXT] '; // TODO
    $output = t($txt);
    return $output;
  }
}
 
/**
 * Implementation of hook_menu().
 */
function fcontrolpanel_menu() {
  $items['admin/build/fcontrolpanel/%/export'] = array(
    'title' => 'export',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fcontrolpanel_export_fcontrol', 3),
    'access arguments' => array('fcontrolpanel export permission'),
    'type' => menu_callback,
  );

  return $items;
}


/**
 * Implementation of hook_theme().
 */
/*
function fcontrolpanel_theme() {
  return array(
    'fcontrolpanel_example' => array(
      'arguments' => array('something' => NULL),
    )
  );
}
// */
 
/**
 * Implementation of theme function.
 */
/*
function theme_fcontrolpanel_example($something) {
  $output = '';
  // add stylesheet
  $path = drupal_get_path('module', 'fcontrolpanel');
  drupal_add_css("$path/fcontrolpanel.css");
  // build $output 
  return $output;
}
// */


//--------------------------------------------------/
// Ctools export hooks                              /
//--------------------------------------------------/

/**
 * Export a myobj and display it in a form.
 */
function fcontrolpanel_export_fcontrol(&$form_state, $fcid) {
  $obj = fcontrolpanel_fcontrol_load($fcid);
  drupal_set_title(check_plain($obj->description));
  $code = fcontrolpanel_fcontrol_export($obj);
  $lines = substr_count($code, "\n");

  $form['export'] = array(
    '#title' => t('Export data'),
    '#type' => 'textarea',
    '#value' => $code,
    '#rows' => $lines,
    '#description' => t('Copy the export text and paste it into another myobj using the import function.'),
  );
  return $form;
}

/**
 * Load a single myobj.
 */
function fcontrolpanel_fcontrol_load($name) {
  ctools_include('export');
  $result = ctools_export_load_object('fcontrolpanel_fcontrol', 'names', array($name)); 
  if (isset($result[$name])) {
    return $result[$name];
  }
}

/**
 * Export a myobj.
 */
function fcontrolpanel_fcontrol_export($obj, $indent = '') {
  ctools_include('export');
  $output = ctools_export_object('fcontrolpanel_fcontrol', $obj, $indent);
  return $output;
}

/**
 * Save a single myobj.
 */
// TODO 
function fcontrolpanel_fcontrol_save(&$myobj) {
    $update = (isset($myobj->oid) && is_numeric($myobj->oid)) ? array('oid') : array();
      return drupal_write_record('myobj', $myobj, $update);
}

/**
 * Implementation of default hook.
 *
 * Note: This function name is defined in .install file,
 *   'default hook' => 'default_mymodule_myobj',  // Function hook name.
 */ 
function fcontrolpanel_default_fcontrolpanel_fcontrol() {
}


//-------------------------------------------------/
// Features hooks                                  /
//-------------------------------------------------/
/**
 * Implementation of hook_features_api().
 */
// TODO 

/**
 * Implementation of hook_features_export().
 */
// TODO 

/**
 * Implementation of hook_features_export_render().
 */
// TODO 

/**
 * Implementation of hook_features_export_options().
 */
// TODO 

/**
 * Implementation of hook_features_revert().
 */
// TODO 

